/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import app.model.Invoice;
import app.model.InvoiceItems;
import app.controller.Controller;


/**
 *
 * @author maysoon
 */
public class CreateNewInvoiceItems extends javax.swing.JFrame {

    MainFrame mainFrame;
    Controller controller;

    /**
     * Creates new form CreateNewInvoiceItems
     */
    public CreateNewInvoiceItems(MainFrame frame) {
        this.mainFrame = frame;
        controller = new Controller(frame);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemNameTxt = new javax.swing.JTextField();
        itemCountTxt = new javax.swing.JTextField();
        submetItemBtn = new javax.swing.JButton();
        submetItemBtn.addActionListener(controller);
        jLabel4 = new javax.swing.JLabel();
        itemPriceTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Invoice Item");

        jLabel2.setText("Item Name");

        jLabel3.setText("Item Count");

        itemNameTxt.setActionCommand("New Item");
        itemNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtActionPerformed(evt);
            }
        });

        itemCountTxt.setActionCommand("New Item Count");
        itemCountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCountTxtActionPerformed(evt);
            }
        });

        submetItemBtn.setText("Submit new Item ");
        submetItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submetItemBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Item price");

        itemPriceTxt.setActionCommand("New Item Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(itemCountTxt)
                    .addComponent(itemNameTxt))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submetItemBtn)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submetItemBtn)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submetItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submetItemBtnActionPerformed
        // TODO add your handling code here:
        int parentinvoiceNumber = (int) mainFrame.getInvTable().getValueAt(mainFrame.getInvTable().getSelectedRow(), 0);
        InvoiceItems item = new InvoiceItems(parentinvoiceNumber, getItemName(), getIPrice(), getCount());
        itemNameTxt.setText("");
        itemCountTxt.setText("");
        itemPriceTxt.setText("");
        mainFrame.getInvoiceItems().add(item);
        for(Invoice invoice : mainFrame.getInvoices()){
            if(invoice.getInvNumber() == parentinvoiceNumber)
                invoice.getItems().add(item);
        }
      mainFrame.addDataInInvoiceTable();
      mainFrame.addDatainInvitemsTable();
      this.dispose();
    }//GEN-LAST:event_submetItemBtnActionPerformed

    private void itemCountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCountTxtActionPerformed

    private void itemNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itemCountTxt;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JTextField itemPriceTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton submetItemBtn;
    // End of variables declaration//GEN-END:variables

    public String getItemName() {
        return itemNameTxt.getText();
    }

    public int getCount() {
        return Integer.parseInt(itemCountTxt.getText());
    }

    public Double getIPrice() {
        return Double.valueOf(itemPriceTxt.getText());
    }

    public void checkIfInvoiceSelected() {

    }

}
